POST http://connectors:8083/connectors
Content-Type: application/json

{
    "name": "debezium-postgres-customer-source-connector",
    "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "database.hostname": "customer-database",
        "database.port": "5434",
        "database.user": "customer_user",
        "database.password": "customer_password",
        "database.dbname" : "customer_db",
        "plugin.name": "pgoutput",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "value.converter.schema.registry.url": "http://schema-registry:8081",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "transforms": "route",
        "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.route.regex": "postgres_.public.customers",
        "transforms.route.replacement": "customers"
    }
}
