POST http://connect:8083/connectors
Content-Type: application/json

{
    "name": "debezium-postgres-inventory-sink-connector",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "connection.url": "jdbc:postgresql://inventory-database:5432/inventory_db",
        "connection.username": "inventory_user",
        "connection.password": "inventory_password",
        "insert.mode": "upsert",
        "delete.enabled": "true",
        "primary.key.mode": "record_key",
        "schema.evolution": "basic",
        "database.time_zone": "UTC",
        "topics": "inventory"
    }
}
