POST http://connect:8083/connectors
Content-Type: application/json

{
    "name": "confluent-jdbc-postgres-inventory-sink-connector",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "connection.url": "jdbc:postgresql://inventory-database:5432/inventory_db",
        "connection.user": "inventory_user",
        "connection.password": "inventory_password",
        "auto.create": "true",
        "auto.evolve": "true",
        "insert.mode": "upsert",
        "pk.mode": "record_key",
        "pk.fields": "id", 
        "delete.enabled": "true",
        "table.name.format": "inventory",
        "topics": "inventory",
        "db.timezone": "UTC"
    }
}