POST http://connectors:8083/connectors
Content-Type: application/json

{
    "name": "debezium-postgres-inventory-source-connector",
    "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "database.hostname": "inventory-database",
        "database.port": "5433",
        "database.user": "inventory_user",
        "database.password": "inventory_password",
        "database.dbname": "inventory_db",
        "plugin.name": "pgoutput",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "value.converter.schema.registry.url": "http://schema-registry:8081",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",

        "transforms": "route",
        "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.route.regex": "postgres_.public.inventory",
        "transforms.route.replacement": "inventory"
    }
}
